// <auto-generated />
using System;
using DevMetrics.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514094147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DevMetrics.Core.Entities.CommitRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateUtc")
                        .HasDatabaseName("IX_Commits_DateUtc");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_Commits_Hash");

                    b.HasIndex("RepositoryId", "DateUtc")
                        .HasDatabaseName("IX_Commits_RepositoryId_DateUtc");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("DevMetrics.Core.Entities.DailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLinesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLinesDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailySummaries_Date");

                    b.HasIndex("RepositoryId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailySummaries_RepositoryId_Date");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("DevMetrics.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastScannedUtc")
                        .HasDatabaseName("IX_Repositories_LastScannedUtc");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_Repositories_Path");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("DevMetrics.Core.Entities.CommitRecord", b =>
                {
                    b.HasOne("DevMetrics.Core.Entities.Repository", "Repository")
                        .WithMany("CommitRecords")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevMetrics.Core.Entities.DailySummary", b =>
                {
                    b.HasOne("DevMetrics.Core.Entities.Repository", "Repository")
                        .WithMany("DailySummaries")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevMetrics.Core.Entities.Repository", b =>
                {
                    b.Navigation("CommitRecords");

                    b.Navigation("DailySummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
